import org.frice.designer.code.AutoCompiler

/**
 * testing the compiler
 * Created by ice1000 on 2016/9/24.
 *
 * @author ice1000
 */
fun main(args: Array<String>) {
	val a = AutoCompiler("""
/**
 * Frice engine class.
 * Auto-generated by Frice engine designer
 * Java
 */
class ThisGame extends org.frice.game.Game {

	public org.frice.game.obj.button.SimpleButton simpleButton64561;


	@Override
	protected void onInit() {
		simpleButton64561 = new org.frice.game.obj.button.SimpleButton("Start", 407.0, 251.0, 80.0, 40.0);
		simpleButton64561.setColorResource(new org.frice.game.resource.graphics.ColorResource(-15728641));
		super.addObject(simpleButton64561);

	}

	public static void main(String[] args) {
		new ThisGame();
	}
}


""", "out/")
	println(a.autoInvoke("main"))
}