// Generated codes

/**
 * Frice engine class.
 * Auto-generated by Frice engine designer
 * Kotlin
 */
class ThisGame() : org.frice.game.Game() {

	lateinit var simpleButton62791: org.frice.game.obj.button.SimpleButton
	lateinit var simpleText3627: org.frice.game.obj.button.SimpleText

	override fun onInit() {
		simpleButton62791 = org.frice.game.obj.button.SimpleButton("Start", 205.0, 199.0, 80.0, 40.0)
		simpleButton62791.colorResource = org.frice.game.resource.graphics.ColorResource(-15728641)
		super<org.frice.game.Game>.addObject(simpleButton62791)
		simpleText3627 = org.frice.game.obj.button.SimpleText("HelloWorld", 245.0, 103.0)
		simpleText3627.colorResource = org.frice.game.resource.graphics.ColorResource(-1)
		super<org.frice.game.Game>.addObject(simpleText3627)

	}

	companion object {
		@JvmStatic fun main(args: Array<String>) {
			ThisGame()
		}
	}
}

