// Generated codes
import org.frice.game.Game
import org.frice.game.obj.button.SimpleButton
import org.frice.game.obj.button.SimpleText
import org.frice.game.obj.sub.ShapeObject
import org.frice.game.resource.graphics.ColorResource
import org.frice.game.utils.graphics.shape.FCircle
import org.frice.game.utils.graphics.shape.FRectangle

/**
 * Frice engine class.
 * Auto-generated by Frice engine designer
 * Kotlin
 */
class ThisGame() : Game() {

	lateinit var simpleButton66240: SimpleButton
	lateinit var simpleText60943: SimpleText
	lateinit var shapeObject669: ShapeObject
	lateinit var shapeObject63353: ShapeObject


	override fun onInit() {
		simpleButton66240 = SimpleButton("GameSatrt", 300.0, 272.0, 100.0, 40.0)
		simpleButton66240.colorResource = ColorResource(-15728641)
		super<Game>.addObject(simpleButton66240)
		simpleText60943 = SimpleText("MyGame", 300.0, 199.0)
		simpleText60943.colorResource = ColorResource(-1)
		super<Game>.addObject(simpleText60943)
		shapeObject669 = ShapeObject(ColorResource(-13948117), FCircle(80.0), 74.0, 100.0)
		super<Game>.addObject(shapeObject669)
		shapeObject63353 = ShapeObject(ColorResource(-13948117), FRectangle(50, 60), 141.0, 477.0)
		super<Game>.addObject(shapeObject63353)

	}

	companion object {
		@JvmStatic fun main(args: Array<String>) {
			ThisGame()
		}
	}
}

