// Generated codes
import org.frice.game.Game
import org.frice.game.obj.button.SimpleText
import org.frice.game.obj.sub.ShapeObject
import org.frice.game.resource.graphics.ColorResource
import org.frice.game.utils.graphics.shape.FCircle
import org.frice.game.utils.graphics.shape.FRectangle

/**
 * Frice engine class.
 * Auto-generated by Frice engine designer
 * Kotlin
 */
class GameFriceProjectource() : Game() {

	lateinit var shapeObject61865: ShapeObject
	lateinit var shapeObject14106: ShapeObject
	lateinit var shapeObject70312: ShapeObject
	lateinit var shapeObject49237: ShapeObject
	lateinit var shapeObject10010: ShapeObject
	lateinit var simpleText11335: SimpleText

	override fun onInit() {
		shapeObject61865 = ShapeObject(ColorResource(-13948117), FCircle(10.0), 427.0, 216.0)
		super<Game>.addObject(shapeObject61865)
		shapeObject14106 = ShapeObject(ColorResource(-13948117), FRectangle(10, 10), 126.0, 224.0)
		super<Game>.addObject(shapeObject14106)
		shapeObject70312 = ShapeObject(ColorResource(-13948117), FCircle(10.0), 103.0, 373.0)
		super<Game>.addObject(shapeObject70312)
		shapeObject49237 = ShapeObject(ColorResource(-13948117), FRectangle(10, 10), 232.0, 331.0)
		super<Game>.addObject(shapeObject49237)
		shapeObject10010 = ShapeObject(ColorResource(-13948117), FCircle(100.0), 119.0, 22.0)
		super<Game>.addObject(shapeObject10010)
		simpleText11335 = SimpleText("Hello World", 119.0, 223.0)
		simpleText11335.colorResource = ColorResource(-13948117)
		super<Game>.addObject(simpleText11335)
	}

	companion object {
		@JvmStatic fun main(args: Array<String>) {
			GameFriceProjectource()
		}
	}
}

