// Generated codes
import org.frice.game.Game
import org.frice.game.obj.button.SimpleText
import org.frice.game.obj.sub.ShapeObject
import org.frice.game.resource.graphics.ColorResource
import org.frice.game.utils.graphics.shape.FCircle
import org.frice.game.utils.graphics.shape.FRectangle

/**
 * Frice engine class.
 * Auto-generated by Frice engine designer
 * Kotlin
 */
class GameFriceProject() : Game() {

	lateinit var text: SimpleText
	lateinit var main: ShapeObject
	lateinit var bottom: ShapeObject


	override fun onInit() {
		text = SimpleText("Hello World", 129.0, 127.0)
		text.colorResource = ColorResource(-1394811)
		super<Game>.addObject(text)
		main = ShapeObject(ColorResource(-1394811), FCircle(100.0), 308.0, 87.0)
		super<Game>.addObject(main)
		bottom = ShapeObject(ColorResource(-13948117), FRectangle(1000, 10), -1.0, 600.0)
		super<Game>.addObject(bottom)

	}

	companion object {
		@JvmStatic fun main(args: Array<String>) {
			GameFriceProject()
		}
	}
}

